# Generated by Django 2.2.16 on 2022-08-13 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220813_0333'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='do not selffollow',
        ),
    ]
